import os

def generate_readme(repo_path, doc_content):
    readme_path = os.path.join(repo_path, "README.md")
    with open(readme_path, 'w') as f:
        f.write(doc_content)


#generate_readme("/path/to/repo", "## Documentation\nThis is the README generated by the builder.")
