from fastapi import FastAPI
from app.repository_reader import read_repository
from app.llm_handler import process_script
from app.documentation_generator import generate_readme

app = FastAPI()

@app.post("/process_repository/")
async def process_repository(repo_path: str):
    # Read the repository
    scripts = read_repository(repo_path)
    
    # Process each script with the LLM handler
    results = {}
    for file, content in scripts.items():
        result = process_script(content)
        results[file] = result
    
    # Generate documentation
    doc_content = "## Documentation\nThis is the README generated by the builder.\n\n"
    for file, result in results.items():
        doc_content += f"### {file}\n{result}\n"
    
    generate_readme(repo_path, doc_content)
    
    return {"status": "success", "results": results}

# Main entry point
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
